### ISSUE TITLE
storage_bat.TestDeleteInstanceWhileAttaching is flaky

### ISSUE THREAD

**Issue by rbradford** [01org/ciao#1009]
```
Logs for failed tests
---------------------
Logs for storage_bat.TestDeleteInstanceWhileAttaching
	storage_bat_test.go:315: Failed to delete volume 36d61091-9063-4fea-8360-80047b5a8511 : failed to launch ciao-cli [volume delete --volume 36d61091-9063-4fea-8360-80047b5a8511] : exit status 255
		F0112 14:28:33.580644   18020 main.go:468] ciao-cli FATAL: Expected HTTP response code [202 204] when accessing [DELETE https://singlevm:8776/v2/af6e94d5fe7c456f94ad886b5e677dae/volumes/36d61091-9063-4fea-8360-80047b5a8511], but got 500 instead
		Internal Server Error
		null
		goroutine 1 [running]:
		github.com/01org/ciao/vendor/github.com/golang/glog.stacks(0x983400, 0xc400000000, 0x110, 0x290)
			/home/rob/src/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:769 +0xa5
		github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).output(0x967080, 0xc400000003, 0xc420320300, 0x941257, 0x7, 0x1d4, 0x0)
			/home/rob/src/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:720 +0x357
		github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).printDepth(0x967080, 0xc400000003, 0x1, 0xc420141e88, 0x1, 0x1)
			/home/rob/src/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:646 +0x126
		github.com/01org/ciao/vendor/github.com/golang/glog.FatalDepth(0x1, 0xc420141e88, 0x1, 0x1)
			/home/rob/src/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:1134 +0x5d
		main.fatalf(0xc420314ee0, 0xd4, 0x0, 0x0, 0x0)
			/home/rob/src/go/src/github.com/01org/ciao/ciao-cli/main.go:132 +0x126
		main.main()
			/home/rob/src/go/src/github.com/01org/ciao/ciao-cli/main.go:468 +0x14d

```

**Comment by rbradford** [comment]
@kaccardi I believe you might have seen this issue before?

**Comment by rbradford** [comment]
@markdryan - looks like a launcher issue:

Here are some log excepts for when it fails:

I see errors in ciao-controller logs that imply that the ephemeral volume is in use when the InstanceDeleted event is received:
```
W0116 16:27:29.643006   25390 client.go:101] Error deleting block device: Error when running: [rbd --id ciao rm 8e94f022-50d3-46cb-b4ee-c8d962d6a3da]: exit status 16: 2017-01-16 16:27:29.615157 7faae0690100 -1 librbd: cannot obtain exclusive lock - not removing
^MRemoving image: 0% complete...failed.
rbd: error: image still has watchers
This means the image is still open or the client using it crashed. Try again after closing/unmapping it or waiting 30s for the crashed client to timeout.

```

But if you investigate the launcher logs it appears that the problem lies with the secondary block device

Creating the instance with rootfs volume (8e94f022-50d3-46cb-b4ee-c8d962d6a3da):

```
I0116 16:27:20.647195   25382 qemu.go:1000] launching qemu with: [-drive file=rbd:rbd/8e94f022-50d3-46cb-b4ee-c8d962d6a3da:id=ciao,if=none,i
d=drive_8e94f022-50d3-46cb-b4ee-c8d962d6a3da,format=raw -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x3,id=device_8e94f022-50d3-46cb-b4ee
-c8d962d6a3da,drive=drive_8e94f022-50d3-46cb-b4ee-c8d962d6a3da -drive file=/var/lib/ciao/instances/37e991e7-fe6e-41a7-b689-851d8fa2bef7/seed
.iso,if=virtio,media=cdrom -netdev type=tap,ifname=svn_98d7702,script=no,downscript=no,id=svn_98d7702,vhost=on -device driver=virtio-net-pci
,netdev=svn_98d7702,mac=02:00:ac:10:00:02 -enable-kvm -cpu host -daemonize -qmp unix:/var/lib/ciao/instances/37e991e7-fe6e-41a7-b689-851d8fa
2bef7/socket,server,nowait -m 128 -smp cpus=2 -display none -vga none -device isa-serial,chardev=gnc0 -chardev socket,port=6652,host=198.51.
100.1,server,id=gnc0,server,nowait]
```

And as expected the volume is attached:

```
I0116 16:27:28.687193   25382 attachvolume_instance.go:63] Mapped instance 37e991e7-fe6e-41a7-b689-851d8fa2bef7 volume 3b6c4c59-328a-46d8-8d61-7de867727077 as /dev/rbd8
I0116 16:27:28.687222   25382 qemu.go:577] Attach command received
I0116 16:27:28.687275   25382 qmp.go:273] {"arguments":{"options":{"driver":"raw","file":{"driver":"file","filename":"/dev/rbd8"},"id":"drive_3b6c4c59-328a-46d8-8d61-7de867727077"}},"execute":"blockdev-add"}
I0116 16:27:28.688386   25382 qmp.go:147] {"return": {}}
I0116 16:27:28.688479   25382 qmp.go:273] {"arguments":{"drive":"drive_3b6c4c59-328a-46d8-8d61-7de867727077","driver":"virtio-blk-pci","id":"device_3b6c4c59-328a-46d8-8d61-7de867727077"},"execute":"device_add"}
I0116 16:27:28.692321   25382 qmp.go:147] {"return": {}}
I0116 16:27:28.718528   25382 instance.go:257] Volume 3b6c4c59-328a-46d8-8d61-7de867727077 attached to instance 37e991e7-fe6e-41a7-b689-851d8fa2bef7
```

But when the instance is deleted cfg.Volumes is empty:

```
I0116 16:27:29.241681   25382 instance.go:343] Unmapping volumes for 37e991e7-fe6e-41a7-b689-851d8fa2bef7
I0116 16:27:29.542349   25382 instance.go:407] Instance goroutine 37e991e7-fe6e-41a7-b689-851d8fa2bef7 waiting for monitor to exit
```

whereas it should look like this (from a run where the test succeeded)

```
I0116 16:26:34.949759   25382 instance.go:343] Unmapping volumes for 8a86c7e0-9977-41d3-8ff3-d4759c863512
I0116 16:26:35.099095   25382 instance.go:352] Unmapping volume d3a9523a-9ab2-4f5d-942a-4b2229c5207f
I0116 16:26:35.099256   25382 instance.go:407] Instance goroutine 8a86c7e0-9977-41d3-8ff3-d4759c863512 waiting for monitor to exit
```

What is ambiguous to me is why failing to umap up the secondary volume is holding up the deletion of the primary.

**Comment by markdryan** [comment]
@rbradford Nice debugging

> But when the instance is deleted cfg.Volumes is empty:

The logs do not necessarily mean the cfg.Volumes is empty.  The failure of id.storageDriver.UnmapVolumeFromNode at instance.go:351 could result in the same logs.  I think this is probably what is happening.  My best guess is that we are trying to unmap volumes from the node before the qemu instance has actually shutdown which would explain the racyness of the test case.  I'll try to add some code that ensures that the qemu instance really is gone before we start unmapping things.
