### ISSUE TITLE
ciao-cli: Fail to update name of an uploaded image

### ISSUE THREAD

**Issue by arturo-garcia-garcia** [01org/ciao#1060]
After add an imag to my cioa cluster, I try to rename it but i receive this error

```
root@controller.example.com ~/ciao/_DeploymentAndDistroPackaging/ansible # ciao-cli image add -file /tmp/clear-8370-cloud.img -name Clear-8370
Created image:
	Name             [Clear-8370]
	Size             [907018240 bytes]
	UUID             [6c0af0a4-e2df-4801-a48c-f199bd996232]
	Status           [active]
	CreatedDate      [2017-01-25T17:14:53.849367464Z]
root@controller.example.com ~/ciao/_DeploymentAndDistroPackaging/ansible # ciao-cli image list
Image #1
	Name             [Clear-8370]
	Size             [907018240 bytes]
	UUID             [6c0af0a4-e2df-4801-a48c-f199bd996232]
	Status           [active]
	CreatedDate      [2017-01-25T17:14:53.849367464Z]

root@controller.example.com ~/ciao/_DeploymentAndDistroPackaging/ansible # ciao-cli image modify -image 6c0af0a4-e2df-4801-a48c-f199bd996232 -name Renamed_image
F0125 17:16:24.436414   14094 image.go:417] ciao-cli FATAL: Could not update image's properties [Expected HTTP response code [200] when accessing [PATCH https://controller.example.com:9292/v2/images/6c0af0a4-e2df-4801-a48c-f199bd996232], but got 404 instead
404 page not found
]
goroutine 1 [running]:
github.com/01org/ciao/vendor/github.com/golang/glog.stacks(0x983400, 0xc400000000, 0x112, 0x166)
	/builddir/build/BUILD/ciao-83/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:769 +0xa5
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).output(0x967060, 0xc400000003, 0xc4202f23c0, 0x941adf, 0x8, 0x1a1, 0x0)
	/builddir/build/BUILD/ciao-83/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:720 +0x357
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).printDepth(0x967060, 0xc400000003, 0x1, 0xc42012fd00, 0x1, 0x1)
	/builddir/build/BUILD/ciao-83/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:646 +0x126
github.com/01org/ciao/vendor/github.com/golang/glog.FatalDepth(0x1, 0xc42012fd00, 0x1, 0x1)
	/builddir/build/BUILD/ciao-83/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:1134 +0x5d
main.fatalf(0x7c9935, 0x29, 0xc42012fdc0, 0x1, 0x1)
	/builddir/build/BUILD/ciao-83/src/github.com/01org/ciao/ciao-cli/main.go:132 +0x126
main.(*imageModifyCommand).run(0xc42007a580, 0xc4200a6060, 0x0, 0x0, 0xc4200a6060, 0x0)
	/builddir/build/BUILD/ciao-83/src/github.com/01org/ciao/ciao-cli/image.go:417 +0x2b5
main.(*command).run(0x9654d0, 0xc4200a6060, 0x0, 0x0, 0xc4200babf8, 0x0)
	/builddir/build/BUILD/ciao-83/src/github.com/01org/ciao/ciao-cli/main.go:58 +0x15b
main.main()
	/builddir/build/BUILD/ciao-83/src/github.com/01org/ciao/ciao-cli/main.go:466 +0xf7
root@controller.example.com ~/ciao/_DeploymentAndDistroPackaging/ansible #

```

**Comment by arturo-garcia-garcia** [comment]
Closing issue since this function is not supported yet
