### ISSUE TITLE
ciao-cli: fail to download an image

### ISSUE THREAD

**Issue by arturo-garcia-garcia** [01org/ciao#1061]
after add an image to the ciao cluster, I try to download it and receive this error

```
root@controller.example.com ~/ciao/_DeploymentAndDistroPackaging/ansible # ciao-cli image add -file /tmp/clear-8370-cloud.img -name Clear-8370
Created image:
	Name             [Clear-8370]
	Size             [907018240 bytes]
	UUID             [6c0af0a4-e2df-4801-a48c-f199bd996232]
	Status           [active]
	CreatedDate      [2017-01-25T17:14:53.849367464Z]
root@controller.example.com ~/ciao/_DeploymentAndDistroPackaging/ansible # ciao-cli image list
Image #1
	Name             [Clear-8370]
	Size             [907018240 bytes]
	UUID             [6c0af0a4-e2df-4801-a48c-f199bd996232]
	Status           [active]
	CreatedDate      [2017-01-25T17:14:53.849367464Z]

root@controller.example.com ~/ciao/_DeploymentAndDistroPackaging/ansible # ciao-cli image download -image 6c0af0a4-e2df-4801-a48c-f199bd996232 -file DownloadedImage.img
F0125 17:19:37.005643   14105 image.go:308] ciao-cli FATAL: Error copying to destination: http: read on closed response body
goroutine 1 [running]:
github.com/01org/ciao/vendor/github.com/golang/glog.stacks(0x983400, 0xc400000000, 0x7d, 0xd0)
	/builddir/build/BUILD/ciao-83/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:769 +0xa5
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).output(0x967060, 0xc400000003, 0xc420426a80, 0x941adf, 0x8, 0x134, 0x0)
	/builddir/build/BUILD/ciao-83/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:720 +0x357
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).printDepth(0x967060, 0xc400000003, 0x1, 0xc420113d20, 0x1, 0x1)
	/builddir/build/BUILD/ciao-83/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:646 +0x126
github.com/01org/ciao/vendor/github.com/golang/glog.FatalDepth(0x1, 0xc420113d20, 0x1, 0x1)
	/builddir/build/BUILD/ciao-83/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:1134 +0x5d
main.fatalf(0x7c5a95, 0x20, 0xc420113db8, 0x1, 0x1)
	/builddir/build/BUILD/ciao-83/src/github.com/01org/ciao/ciao-cli/main.go:132 +0x126
main.(*imageDownloadCommand).run(0xc42001a580, 0xc42000c140, 0x0, 0x0, 0x944d80, 0xc420016e80)
	/builddir/build/BUILD/ciao-83/src/github.com/01org/ciao/ciao-cli/image.go:308 +0x2ac
main.(*command).run(0x9654d0, 0xc42000c140, 0x0, 0x0, 0xc420098c28, 0x0)
	/builddir/build/BUILD/ciao-83/src/github.com/01org/ciao/ciao-cli/main.go:58 +0x15b
main.main()
	/builddir/build/BUILD/ciao-83/src/github.com/01org/ciao/ciao-cli/main.go:466 +0xf7


```

**Comment by arturo-garcia-garcia** [comment]
Closing issue since this functionality is not supported yet
