### ISSUE TITLE
ciao-ceploy: ansible does not catch a panic

### ISSUE THREAD

**Issue by arturo-garcia-garcia** [01org/ciao#1124]
When deploying ciao using ansible. it reports that ends succesfully, but when running with verosity, a panic raise but is not catch
```

TASK [ciao-controller : Check if "Clear Cloud" exists] *************************
    task path: /root/ciao/_DeploymentAndDistroPackaging/ansible-clear/roles/ciao-controller/tasks/upload_images.yml:19
    Using module file /usr/lib/python3.6/site-packages/ansible/modules/core/commands/command.py
    <controller.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
    <controller.example.com> EXEC /bin/sh -c 'CIAO_CONTROLLER=controller.example.com CIAO_IDENTITY=https://controller.example.com:35357 CIAO_USERNAME=admin CIAO_PASSWORD=adminUserPassword CIAO_TENANT_NAME=admin CIAO_CA_CERT_FILE=certificates/keyston        e/keystone_cert.pem /usr/bin/python && sleep 0'
    ok: [controller.example.com] => {
        "changed": false,
        "cmd": "/root/ciao/_DeploymentAndDistroPackaging/ansible-clear/fetch/ciao-cli image show -image df3768da-31f5-4ba6-82f0-127a1a705169",
        "delta": "0:00:00.134559",
        "end": "2017-02-03 22:52:22.941965",
        "failed": false,
        "failed_when_result": false,
        "invocation": {
            "module_args": {
                "_raw_params": "/root/ciao/_DeploymentAndDistroPackaging/ansible-clear/fetch/ciao-cli image show -image df3768da-31f5-4ba6-82f0-127a1a705169",
                "_uses_shell": true,
                "chdir": null,
                "creates": null,
                "executable": null,
                "removes": null,
                "warn": true
            },
            "module_name": "command"
        },
        "rc": 2,
        "start": "2017-02-03 22:52:22.807406",
        "stderr": "panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5cdc18]\n\ngoroutine 1 [running]:\npanic(0x759340, 0xc4200120d0)\n\t/usr/lib/g        olang/src/runtime/panic.go:500 +0x1a1\ncrypto/x509.(*CertPool).AddCert(0x0, 0xc4200fe000)\n\t/usr/lib/golang/src/crypto/x509/cert_pool.go:89 +0x48\ncrypto/x509.(*CertPool).AppendCertsFromPEM(0x0, 0xc4200ee45b, 0x0, 0x200, 0x65b)\n        \t/usr/lib/golang/src/crypto/x509/cert_pool.go:128 +0x161\nmain.prepareForCommand()\n\t/builddir/build/BUILD/ciao-85/src/github.com/01org/ciao/ciao-cli/main.go:422 +0x4e6\nmain.(*command).run(0x965450, 0xc42000c1d0, 0x0, 0x0, 0xc4        2009cc08, 0x0)\n\t/builddir/build/BUILD/ciao-85/src/github.com/01org/ciao/ciao-cli/main.go:57 +0x120\nmain.main()\n\t/builddir/build/BUILD/ciao-85/src/github.com/01org/ciao/ciao-cli/main.go:466 +0xf7",
        "stdout": "",
        "stdout_lines": [],
        "warnings": []
    }

```

**Comment by albertomurillo** [comment]
I wonder if this bug is still valid.

The issue here is that the `ciao-cli` binary was installed from the packages on the controller node and transfered to the deployment node.

We do not longer provide this method of installation and binaries are compiled on the deployment node and transferred to the controller node instead.

Please verify this is no longer reproducible and close this issue.

**Comment by arturo-garcia-garcia** [comment]
Issue still present using ciao code with tag 86

```

[root@deployer ciao]# git branch
* (detached from 86)
  master
[root@deployer ciao]# 

```

Issue present in the 3 distros

```
TASK [ciao-controller : Check if "Clear Cloud" exists] *************************
    task path: /root/ciao/_DeploymentAndDistroPackaging/ansible-ubuntu/roles/ciao-controller/tasks/upload_images.yml:16
    Using module file /usr/lib/python3.6/site-packages/ansible/modules/core/commands/command.py
    <controller-ubuntu.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
    <controller-ubuntu.example.com> EXEC /bin/sh -c 'CIAO_CONTROLLER=controller-ubuntu.example.com CIAO_IDENTITY=https://controller-ubuntu.example.com:35357 CIAO_USERNAME=admin CIAO_PASSWORD=adminUserPassword CIAO_TENANT_NAME=admin CIAO_CA_CERT_FILE=certificates/keyston        e/keystone_cert.pem /usr/bin/python && sleep 0'
    ok: [controller-ubuntu.example.com] => {
        "changed": false,
        "cmd": "/tmp/go/bin/ciao-cli image show -image df3768da-31f5-4ba6-82f0-127a1a705169",
        "delta": "0:00:00.134370",
        "end": "2017-02-16 17:26:09.008734",
        "failed": false,
        "failed_when_result": false,
        "invocation": {
            "module_args": {
                "_raw_params": "/tmp/go/bin/ciao-cli image show -image df3768da-31f5-4ba6-82f0-127a1a705169",
                "_uses_shell": true,
                "chdir": null,
                "creates": null,
                "executable": null,
                "removes": null,
                "warn": true
            },
            "module_name": "command"
        },
        "rc": 2,
        "start": "2017-02-16 17:26:08.874364",
        "stderr": "panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5d1b68]\n\ngoroutine 1 [running]:\npanic(0x7a0160, 0xc4200140d0)\n\t/usr/lib/g        olang/src/runtime/panic.go:500 +0x1a1\ncrypto/x509.(*CertPool).AddCert(0x0, 0xc420104000)\n\t/usr/lib/golang/src/crypto/x509/cert_pool.go:89 +0x48\ncrypto/x509.(*CertPool).AppendCertsFromPEM(0x0, 0xc4200f445b, 0x0, 0x200, 0x65b)\n        \t/usr/lib/golang/src/crypto/x509/cert_pool.go:128 +0x161\nmain.prepareForCommand()\n\t/tmp/go/src/github.com/01org/ciao/ciao-cli/main.go:423 +0x4e6\nmain.(*command).run(0x9d0c00, 0xc42000c180, 0x0, 0x0, 0xc42009cc08, 0x0)\n\t/tmp        /go/src/github.com/01org/ciao/ciao-cli/main.go:57 +0x120\nmain.main()\n\t/tmp/go/src/github.com/01org/ciao/ciao-cli/main.go:467 +0xf7",
        "stdout": "",
        "stdout_lines": [],
        "warnings": []
    }


```
