### ISSUE TITLE
api: block storage: bootable volume flag inconsistent

### ISSUE THREAD

**Issue by jorgevgut** [01org/ciao#1191]
Hi,

I'm testing out the bootable volume feature through the webui and I'm sending this data in a POST request to create a bootable volume.
```
{volume:{name:testboot,
size:1,
description:"test boot",
bootable:"true",
imageRef:"df3768da-31f5-4ba6-82f0-127a1a705169"}}
```

controller's POST response is the following (endpoint is /v2/{tenant}/volumes POST method):
```
{"volume":{
"status":"available",
"migration_status":null,
"user_id":"6ce8104700414973b7954defb582739f",
"attachments":[],
"links":[],
"availability_zone":null,
"bootable":"true",
"encrypted":false,
"created_at":"2017-02-22T00:04:49.294973562Z",
"description":null,
"updated_at":null,
"volume_type":null,
"name":null,
"replication_status":"",
"consistencygroup_id":null,
"source_volid":null,
"snapshot_id":null,
"multiattach":false,
"metadata":null,
"id":"ec2b330b-ce74-4a8d-908a-c76ae5d44ed1",
"size":1}}
```

This response clearly states that bootable value is set as "true".
However /v2/{tenant}/volumes/detail endpoint (Method GET)
does not show bootable as true, but empty which does not match the response from the POST endpoint.
```
{
migration_status: null,
attachments: null,
links: null,
availability_zone: null,
os-vol-host-attr:host: "",
encrypted: false,
updated_at: null,
replication_status: "",
snapshot_id: null,
id: "ec2b330b-ce74-4a8d-908a-c76ae5d44ed1",
size: 1,
user_id: "",
os-vol-tenant-attr:tenant_id: "6ce8104700414973b7954defb582739f",
os-vol-mig-status-attr:migstat: null,
metadata: null,
status: "available",
description: "test boot",
multiattach: false,
source_volid: null,
consistencygroup_id: null,
os-vol-mig-status-attr:name_id: null,
name: "testboot",
bootable: "",
created_at: "2017-02-22T00:04:49.294973562Z",
volume_type: null
}
```

Impact: I currently can't validate if request to create the bootable volume is working properly due to inconsistency in the responses from the api endpoints.

**Comment by rbradford** [comment]
@jorgevgut feel free to test this change if you're interested.

**Comment by jorgevgut** [comment]
Thank you @rbradford  I'll test it today and let know the outcome.

**Comment by jorgevgut** [comment]
@rbradford I'm confirming the change is working on the webui, here is an attached image that shows that the response is reporting the bootable field successfully.
![selection_004](https://cloud.githubusercontent.com/assets/2206062/23227394/6bc8dc96-f8fe-11e6-8a6f-0cf4abbfbe7f.png)

However I would like to report that I'm unable to see these details in the ciao-cli after running volume list, or volume show commands.
```
root@singlevm:~/bin# ciao-cli volume show -volume testboot
F0222 18:54:33.406639   22440 main.go:469] ciao-cli FATAL: Expected HTTP response code [200] when accessing [GET https://singlevm:8776/v2/5a9773bb8a3646a7bebdcab67bbf3f84/volumes/testboot], but got 500 instead
Internal Server Error
null
goroutine 1 [running]:
github.com/01org/ciao/vendor/github.com/golang/glog.stacks(0x9eeb00, 0xc400000000, 0xed, 0x267)
        /root/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:769 +0xa5
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).output(0x9d27c0, 0xc400000003, 0xc4200e4540, 0x9abbb3, 0x7, 0x1d5, 0x0)
        /root/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:720 +0x357
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).printDepth(0x9d27c0, 0xc400000003, 0x1, 0xc420155e88, 0x1, 0x1)
        /root/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:646 +0x126
github.com/01org/ciao/vendor/github.com/golang/glog.FatalDepth(0x1, 0xc420155e88, 0x1, 0x1)
        /root/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:1134 +0x5d
main.fatalf(0xc4204a3080, 0xb1, 0x0, 0x0, 0x0)
        /root/src/github.com/01org/ciao/ciao-cli/main.go:133 +0x126
main.main()
        /root/src/github.com/01org/ciao/ciao-cli/main.go:469 +0x14d
root@singlevm:~/bin# ciao-cli volume list
Volume #1
        Name             [Storage for instance: c1d66b32-dd5f-49ee-9680-fef260e6ba1b]
        Size             [1 GB]
        UUID             [53ea7bf9-1820-4a56-ad0d-155e2dc06f59]
        Status           [in-use]
        Description      []

root@singlevm:~/bin# 

```
May I ask if I'm using the cli properly? or is this a different issue?
Thanks again for your help.
