### ISSUE TITLE
Deleting external-ips and pools is racy

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#1282]
Here's an example in which I try to unmap an external-ip and delete the pool immediately afterwards.

```
$ ciao-cli external-ip list
# ExternalIP   InternalIP
1 198.51.100.2 172.16.0.2

$ CIAO_USER=$CIAO_ADMIN_USERNAME CIAO_ADMIN=$CIAO_ADMIN_PASSWORD ciao-cli external-ip unmap --address 198.51.100.2 && ciao-cli pool delete --name k8s-pool
Requested unmap of: 198.51.100.2
F0518 17:37:07.352590    2423 external-ips.go:607] ciao-cli FATAL: Invalid Link returned from controller
goroutine 1 [running]:
github.com/01org/ciao/vendor/github.com/golang/glog.stacks(0xc42017a900, 0xc42019c380, 0x69, 0xd3)
	/home/markus/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:769 +0xa7
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).output(0xa65cc0, 0xc400000003, 0xc4200a6bb0, 0xa28ddb, 0xf, 0x25f, 0x0)
	/home/markus/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:720 +0x36b
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).printDepth(0xa65cc0, 0x3, 0x1, 0xc42009fdb0, 0x1, 0x1)
	/home/markus/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:646 +0x12d
github.com/01org/ciao/vendor/github.com/golang/glog.FatalDepth(0x1, 0xc42009fdb0, 0x1, 0x1)
	/home/markus/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:1134 +0x5d
main.fatalf(0x875f7e, 0x25, 0x0, 0x0, 0x0)
	/home/markus/go-fork/src/github.com/01org/ciao/ciao-cli/main.go:133 +0x11d
main.(*poolDeleteCommand).run(0xc420062bd0, 0xc420010130, 0x0, 0x0, 0x0, 0x0)
	/home/markus/go-fork/src/github.com/01org/ciao/ciao-cli/external-ips.go:607 +0x347
main.(*command).run(0xa63fd8, 0xc420010130, 0x0, 0x0, 0xc420089068, 0x4)
	/home/markus/go-fork/src/github.com/01org/ciao/ciao-cli/main.go:58 +0x156
main.main()
	/home/markus/go-fork/src/github.com/01org/ciao/ciao-cli/main.go:467 +0x105
```

I try again and get a different error.  You can see that the external-ip has been deleted.

```
$ CIAO_USER=$CIAO_ADMIN_USERNAME CIAO_ADMIN=$CIAO_ADMIN_PASSWORD ciao-cli external-ip unmap --address 198.51.100.2 && ciao-cli pool delete --name k8s-pool
F0518 17:37:12.062654    2430 external-ips.go:266] ciao-cli FATAL: Address Not Found
goroutine 1 [running]:
github.com/01org/ciao/vendor/github.com/golang/glog.stacks(0xc42017b400, 0xc4200fc1c0, 0x55, 0xd3)
	/home/markus/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:769 +0xa7
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).output(0xa65cc0, 0xc400000003, 0xc42025ac60, 0xa28ddb, 0xf, 0x10a, 0x0)
	/home/markus/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:720 +0x36b
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).printDepth(0xa65cc0, 0x3, 0x1, 0xc42009fdb0, 0x1, 0x1)
	/home/markus/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:646 +0x12d
github.com/01org/ciao/vendor/github.com/golang/glog.FatalDepth(0x1, 0xc42009fdb0, 0x1, 0x1)
	/home/markus/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:1134 +0x5d
main.fatalf(0x86bb9e, 0x11, 0x0, 0x0, 0x0)
	/home/markus/go-fork/src/github.com/01org/ciao/ciao-cli/main.go:133 +0x11d
main.(*externalIPUnMapCommand).run(0xc420062a80, 0xc420010130, 0x0, 0x0, 0x0, 0x0)
	/home/markus/go-fork/src/github.com/01org/ciao/ciao-cli/external-ips.go:266 +0x342
main.(*command).run(0xa63fd0, 0xc420010130, 0x0, 0x0, 0xc4200891a8, 0x4)
	/home/markus/go-fork/src/github.com/01org/ciao/ciao-cli/main.go:58 +0x156
main.main()
	/home/markus/go-fork/src/github.com/01org/ciao/ciao-cli/main.go:467 +0x105
```

The pool however cannot be deleted

```
$ ciao-cli pool delete --name k8s-pool
F0518 17:37:18.143944    2438 external-ips.go:607] ciao-cli FATAL: Invalid Link returned from controller
goroutine 1 [running]:
github.com/01org/ciao/vendor/github.com/golang/glog.stacks(0xc4201be700, 0xc4202220e0, 0x69, 0xd3)
	/home/markus/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:769 +0xa7
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).output(0xa65cc0, 0xc400000003, 0xc420388000, 0xa28ddb, 0xf, 0x25f, 0x0)
	/home/markus/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:720 +0x36b
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).printDepth(0xa65cc0, 0x3, 0x1, 0xc4200afdb0, 0x1, 0x1)
	/home/markus/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:646 +0x12d
github.com/01org/ciao/vendor/github.com/golang/glog.FatalDepth(0x1, 0xc4200afdb0, 0x1, 0x1)
	/home/markus/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:1134 +0x5d
main.fatalf(0x875f7e, 0x25, 0x0, 0x0, 0x0)
	/home/markus/go-fork/src/github.com/01org/ciao/ciao-cli/main.go:133 +0x11d
main.(*poolDeleteCommand).run(0xc4200f6b60, 0xc420090040, 0x0, 0x0, 0x0, 0x0)
	/home/markus/go-fork/src/github.com/01org/ciao/ciao-cli/external-ips.go:607 +0x347
main.(*command).run(0xa63fd8, 0xc420090040, 0x0, 0x0, 0xc420097198, 0x4)
	/home/markus/go-fork/src/github.com/01org/ciao/ciao-cli/main.go:58 +0x156
main.main()
	/home/markus/go-fork/src/github.com/01org/ciao/ciao-cli/main.go:467 +0x105
```

It still exists

```
$ ciao-cli pool list
# Name
1 k8s-pool

$ ciao-cli pool show --name ks8-pool
	UUID: 
	Name: 
	Free IPs: 0
	Total IPs: 0
$ ciao-cli external-ip list
# ExternalIP InternalIP
```

But is empty and cannot be deleted

**Comment by markdryan** [comment]
Okay, this is my fault.  I wasn't specifying the credentials correctly.  Closing.
