### ISSUE TITLE
cnci never started again after start failure

### ISSUE THREAD

**Issue by rbradford** [01org/ciao#1416]
If you create cluster where there is no network node, starting the CNCI fails and then gives cyptic errors after subsequently. And it continues to fail even after adding a network node:

```
rbradfor@ciao-ctl:~/go/src/github.com/01org/ciao$ ciao-cli instance add -workload bb90b4ff-09d5-450f-bd94-85c48b5d3c31
F0904 12:38:49.296045   25542 instance.go:528] ciao-cli FATAL: HTTP Error [500] for [POST https://ciao-ctl:8889/v2.1/d56433f2-1a00-4b97-a7d1-838ff5221e53/servers]: {"error":{"code":500,"name":"Internal Server Error","message":"Error creating instance: expecting concentrator added g
ot cnci start failure"}}
goroutine 1 [running]:
github.com/01org/ciao/vendor/github.com/golang/glog.stacks(0xc4203fa200, 0xc420480000, 0x133, 0x184)
        /home/rbradfor/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:769 +0xcf
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).output(0xaa51a0, 0xc400000003, 0xc42009a2c0, 0xa5f516, 0xb, 0x210, 0x0)
        /home/rbradfor/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:720 +0x345
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).printDepth(0xaa51a0, 0x3, 0x1, 0xc42011f7c0, 0x1, 0x1)
        /home/rbradfor/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:646 +0x12a
github.com/01org/ciao/vendor/github.com/golang/glog.FatalDepth(0x1, 0xc42011f7c0, 0x1, 0x1)
        /home/rbradfor/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:1134 +0x5d
main.fatalf(0xc42000ae00, 0xf4, 0x0, 0x0, 0x0)
        /home/rbradfor/go/src/github.com/01org/ciao/ciao-cli/main.go:113 +0x11d
main.(*instanceAddCommand).run(0xc4200f0180, 0xc420010180, 0x0, 0x0, 0xc420010180, 0x0)
        /home/rbradfor/go/src/github.com/01org/ciao/ciao-cli/instance.go:528 +0x6a0
main.(*command).run(0xaa32c0, 0xc420010180, 0x0, 0x0, 0xc420087b88, 0x0)
        /home/rbradfor/go/src/github.com/01org/ciao/ciao-cli/main.go:58 +0x154
main.main()
        /home/rbradfor/go/src/github.com/01org/ciao/ciao-cli/main.go:471 +0x105
```

```
rbradfor@ciao-ctl:~/go/src/github.com/01org/ciao$ ciao-cli instance add -workload bb90b4ff-09d5-450f-bd94-85c48b5d3c31
E0904 12:38:59.049711   25596 main.go:222] ciao-cli ERROR: Could not send HTTP request Post https://ciao-ctl:8889/v2.1/d56433f2-1a00-4b97-a7d1-838ff5221e53/servers: EOF
F0904 12:38:59.050981   25596 instance.go:528] ciao-cli FATAL: Post https://ciao-ctl:8889/v2.1/d56433f2-1a00-4b97-a7d1-838ff5221e53/servers: EOF
goroutine 1 [running]:
github.com/01org/ciao/vendor/github.com/golang/glog.stacks(0xc420404100, 0xc42000ad00, 0x91, 0xfe)
        /home/rbradfor/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:769 +0xcf
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).output(0xaa51a0, 0xc400000003, 0xc4200a82c0, 0xa5f516, 0xb, 0x210, 0x0)
        /home/rbradfor/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:720 +0x345
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).printDepth(0xaa51a0, 0x3, 0x1, 0xc42012b7c0, 0x1, 0x1)
        /home/rbradfor/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:646 +0x12a
github.com/01org/ciao/vendor/github.com/golang/glog.FatalDepth(0x1, 0xc42012b7c0, 0x1, 0x1)
        /home/rbradfor/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:1134 +0x5d
main.fatalf(0xc420024360, 0x51, 0x0, 0x0, 0x0)
        /home/rbradfor/go/src/github.com/01org/ciao/ciao-cli/main.go:113 +0x11d
main.(*instanceAddCommand).run(0xc420100180, 0xc420010180, 0x0, 0x0, 0xc420010180, 0x0)
        /home/rbradfor/go/src/github.com/01org/ciao/ciao-cli/instance.go:528 +0x6a0
main.(*command).run(0xaa32c0, 0xc420010180, 0x0, 0x0, 0xc420095b88, 0x0)
        /home/rbradfor/go/src/github.com/01org/ciao/ciao-cli/main.go:58 +0x154
main.main()
```

**Comment by rbradford** [comment]
After #1418, I can launch the cnci fine once the network node is setup. So this is fixed.
