### ISSUE TITLE
test-cases should dump stder when it receives a sigkill

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#328]
Travis kills programs that take longer than 10 minutes to execute.  If a unit test-case hangs, that test case will hang test-cases as well.  test-cases will sit their until it receives the SIGQUIT, at which point it will exit without printed any output.  In this case, it's not really clear what went wrong.  It would be nice if test-cases could trap SIGQUITs and exit with some better indication of what went wrong, perhaps dump the stderr/stdout of the failing go test invocation.

**Comment by markdryan** [comment]
I tried this but it doesn't fix the problem.  I can force test-cases to quit when receiving a SIGKILL but by the time is quits travis, has already killed the build and so it doesn't have enough time to log any errors.  One thing I might try is outputting something from test-cases every so often to stop travis killing the build.  Then I could introduce a timeout into test-cases itself.

**Comment by markdryan** [comment]
Okay, so this is much better.  @tpepper check out this build

https://travis-ci.org/markdryan/ciao/jobs/141718321

test-cases aborts the unit tests after 9 minutes.  You can see that the first test case that didn't run was TestDeleteInstance.  Also if you check the stack traces at the bottom you see

```
goroutine 651 [semacquire, 8 minutes]:

sync.runtime_Semacquire(0xc8200a6f34)

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/sema.go:47 +0x26

sync.(*Mutex).Lock(0xc8200a6f30)

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/sync/mutex.go:83 +0x1c4

github.com/01org/ciao/testutil.(*SsntpTestServer).AddCmdChan(0xf5a320, 0xb72205, 0xc8203be400)

	/home/travis/gopath/src/github.com/01org/ciao/testutil/server.go:53 +0x7a

github.com/01org/ciao/ciao-controller.TestDeleteInstance(0xc82066e000)

	/home/travis/gopath/src/github.com/01org/ciao/ciao-controller/controller_test.go:274 +0x113

testing.tRunner(0xc82066e000, 0xf3dc90)

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:473 +0x98

created by testing.RunTests

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:582 +0x892
```

which suggests that things are blocked in AddCmdChan.  I'm testing here with your old code that got stuck on travis.  It was a good test case for test-cases.

I'll review and send a PR on Monday.
