### ISSUE TITLE
Testutils unit tests hang occassionally.

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#580]
This hang occurred on a go tip build.

```
testutil           TestTenantAdded                          0.00s      PASS    

testutil           TestReconnects                           N/A        NOT RUN 

testutil           TestTenantRemoved                        N/A        NOT RUN 

testutil           TestPublicIPAssigned                     N/A        NOT RUN 

testutil           TestNewSsntpTestControllerConnectionArgs N/A        NOT RUN 

testutil           TestControllerErrorChan                  N/A        NOT RUN 

testutil           TestControllerErrorChanTimeout           N/A        NOT RUN 

testutil           TestControllerEventChan                  N/A        NOT RUN 

testutil           TestControllerEventChanTimeout           N/A        NOT RUN 

testutil           TestControllerCmdChan                    N/A        NOT RUN 

testutil           TestControllerCmdChanTimeout             N/A        NOT RUN 

testutil           TestControllerCloseChans                 N/A        NOT RUN 

testutil           TestStartIdentityServer                  N/A        NOT RUN 

testutil           TestServerStatusChan                     N/A        NOT RUN 

testutil           TestServerStatusChanTimeout              N/A        NOT RUN 

testutil           TestServerErrorChan                      N/A        NOT RUN 

testutil           TestServerErrorChanTimeout               N/A        NOT RUN 

testutil           TestServerEventChan                      N/A        NOT RUN 

testutil           TestServerEventChanTimeout               N/A        NOT RUN 

testutil           TestServerCmdChan                        N/A        NOT RUN 

testutil           TestServerCmdChanTimeout                 N/A        NOT RUN 

testutil           TestServerCloseChans                     N/A        NOT RUN 

testutil           TestRoleToTestCert                       N/A        NOT RUN 
```

And here are the stack traces

```
SIGABRT: abort

PC=0x45d151 m=0

goroutine 0 [idle]:

runtime.futex(0x8b65d0, 0x0, 0x0, 0x0, 0x0, 0x7f2a00000000, 0x0, 0x0, 0x7ffda061a168, 0x40eeab, ...)

	/home/travis/.gimme/versions/go/src/runtime/sys_linux_amd64.s:387 +0x21

runtime.futexsleep(0x8b65d0, 0x0, 0xffffffffffffffff)

	/home/travis/.gimme/versions/go/src/runtime/os_linux.go:45 +0x62

runtime.notesleep(0x8b65d0)

	/home/travis/.gimme/versions/go/src/runtime/lock_futex.go:145 +0x6b

runtime.stopm()

	/home/travis/.gimme/versions/go/src/runtime/proc.go:1594 +0xad

runtime.findrunnable(0xc420027300, 0x0)

	/home/travis/.gimme/versions/go/src/runtime/proc.go:2021 +0x248

runtime.schedule()

	/home/travis/.gimme/versions/go/src/runtime/proc.go:2120SIGABRT: abort +0x151

PC=runtime.park_m(0x4cd9530xc42009a680 m=)

2	

/home/travis/.gimme/versions/go/src/runtime/proc.go:

2183 +0xa0

goroutine runtime.mcall(00x7ffda061a300 [)

idle	]:

/home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:240 +0x5b

goroutine 1 [semacquire, 8 minutes]:

runtime.futex(0xa1d778, 0x0, 0x7f26108d5d88, 0x0sync.runtime_Semacquire, (0x7f26000000000xc420329744, )

0x4cd676	, /home/travis/.gimme/versions/go/src/runtime/sema.go0x3c:, 470x0 +, 0x300x7f26108d5dd0

, 0x4836a0, ...sync.(*WaitGroup).Wait)

(0xc420329738)

	/home/travis/.gimme/versions/go/src/sync/waitgroup.go:131 +0x73

github.com/01org/ciao/ssntp.(*Server).Stop(0xc4203296a0)

		/home/travis/.gimme/versions/go/src/runtime/sys_linux_amd64.s/home/travis/gopath/src/github.com/01org/ciao/ssntp/server.go::348388 + +0x23c0x23

github.com/01org/ciao/ciao-scheduler.ssntpTestsTeardown()

runtime.futexsleep(0xa1d778	, /home/travis/gopath/src/github.com/01org/ciao/ciao-scheduler/scheduler_ssntp_test.go:0x7f2600000000611,  +0xdf84758000x26e)

	github.com/01org/ciao/ciao-scheduler.TestMain/home/travis/.gimme/versions/go/src/runtime/os_linux.go(:0xc42046dee862)

 +0xd7	

/home/travis/gopath/src/github.com/01org/ciao/ciao-scheduler/scheduler_internal_test.go:170runtime.notetsleep_internal +(0x4d0xa1d778

, 0xdf8475800main.main, (0x0)

)

		github.com/01org/ciao/ciao-scheduler/_test/_testmain.go/home/travis/.gimme/versions/go/src/runtime/lock_futex.go::164174 + +0x1bd0xd0

runtime.notetsleep(

0xa1d778, goroutine 0xdf847580017,  [0xa0d9277601syscall)

, 	8/home/travis/.gimme/versions/go/src/runtime/lock_futex.go minutes:, locked to thread194]:

 +0x56

runtime.goexit()

runtime.sysmon	(/home/travis/.gimme/versions/go/src/runtime/asm_amd64.s)

:2163 +	0x1/home/travis/.gimme/versions/go/src/runtime/proc.go

:3618

 +goroutine 0x1345

 [chan receive]:

runtime.mstart1()

	/home/travis/.gimme/versions/go/src/runtime/proc.go:1126 +0x11egithub.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).flushDaemon

(0x8b5c80runtime.mstart)

()

	/home/travis/gopath/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go	:/home/travis/.gimme/versions/go/src/runtime/proc.go882: +10960x7a +

0x64

created by github.com/01org/ciao/vendor/github.com/golang/glog.init.1

	/home/travis/gopath/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:410 +goroutine 0x21d1

 [semacquire

, 8goroutine  minutes161]:

 [IO wait, 8 minutes]:

sync.runtime_Semacquire(net.runtime_pollWait0xc42048765c()

0x7f2a230dbc00	, /home/travis/.gimme/versions/go/src/runtime/sema.go0x72:, 470x9 +)

0x30

	/home/travis/.gimme/versions/go/src/runtime/netpoll.go:sync.(*WaitGroup).Wait160( +0xc4204876500x59)

	net.(*pollDesc).wait/home/travis/.gimme/versions/go/src/sync/waitgroup.go(:0xc42005fb10131,  +0x730x72

, 0x8962c0, 0x893448main.(*builder).do)

(0xc420425480	, /home/travis/.gimme/versions/go/src/net/fd_poll_runtime.go0xc4201f04e0:)

75 +0x38

	net.(*pollDesc).waitRead/home/travis/.gimme/versions/go/src/cmd/go/build.go(:0xc42005fb101365,  +0xc4202128000x4ce, 

0x400)

main.runTest	(/home/travis/.gimme/versions/go/src/net/fd_poll_runtime.go0xa167c0:, 800xc42000c0a0 +, 0x340x6

, 0x6)

net.(*netFD).Read(0xc42005fab0, 0xc420212800, 0x400, 0x400, 0x0, 0x8962c0, 0x893448)

		/home/travis/.gimme/versions/go/src/cmd/go/test.go/home/travis/.gimme/versions/go/src/net/fd_unix.go::621243 + +0x12b00x181

main.mainnet.(*conn).Read(()

0xc420034880, 0xc420212800, 	0x400/home/travis/.gimme/versions/go/src/cmd/go/main.go, :0x400182,  +0x00x607, 

0x0, 0x0)

	/home/travis/.gimme/versions/go/src/net/net.go

:173goroutine  +170x70 [

syscall, 8crypto/tls.(*block).readFromUntil minutes(, locked to thread0xc420354060]:

, 0x7f2a230dc080, runtime.goexit0xc420034880(, )

0x5, 	0xc420034880/home/travis/.gimme/versions/go/src/runtime/asm_amd64.s, :0x4533002163)

 +0x1	

/home/travis/.gimme/versions/go/src/crypto/tls/conn.go:

472goroutine  +50x91 [

syscall, 8crypto/tls.(*Conn).readRecord minutes(]:

0xc420343180, 0x75c917, 0xc420343280, os/signal.signal_recv0x337aaf1f()

0x0)

	/home/travis/.gimme/versions/go/src/crypto/tls/conn.go	:/home/travis/.gimme/versions/go/src/runtime/sigqueue.go574: +1160xc4 +

0x108

crypto/tls.(*Conn).Read(os/signal.loop0xc420343180(, )

0xc420371000, 	0x1000/home/travis/.gimme/versions/go/src/os/signal/signal_unix.go, :0x100022,  +0x00x22, 

0x0, created by 0x0os/signal.init.1)

		/home/travis/.gimme/versions/go/src/crypto/tls/conn.go/home/travis/.gimme/versions/go/src/os/signal/signal_unix.go::110928 + +0x1160x41

bufio.(*Reader).fillgoroutine (270xc4201ffe00 [)

syscall, 	8/home/travis/.gimme/versions/go/src/bufio/bufio.go minutes:]:

97 +0x10b

syscall.Syscall6(0xf7bufio.(*Reader).Read, (0x10xc4201ffe00, , 0x26070xc420459b30, , 0xc4200345780x1, , 0x10000040x9, , 0x00x44, , 0x00x77, , 0x4e8e790x0, )

0xc420116248, 	0x4775ee/home/travis/.gimme/versions/go/src/bufio/bufio.go)

:	209/home/travis/.gimme/versions/go/src/syscall/asm_linux_amd64.s +:0x18344

 +0x5io.ReadAtLeast

(0x894840, os.(*Process).blockUntilWaitable0xc4201ffe00(, 0xc4204595300xc420459b30, , 0x00x1, , 0x7ccd400x9, , 0x4c33b00x1)

, 0x38980f722d1b	, /home/travis/.gimme/versions/go/src/os/wait_waitid.go0x4102b0:, 280xc4203c5c68 +)

0xa8

	os.(*Process).wait/home/travis/.gimme/versions/go/src/io/io.go(:0xc420459530307,  +0x00xa4, 

0x0, io.ReadFull0x0()

0x894840	, /home/travis/.gimme/versions/go/src/os/exec_unix.go0xc4201ffe00:, 220xc420459b30 +, 0x4d0x1

, 0x9os.(*Process).Wait, (0xc4203555900xc420459530, , 0x00xc4203ca418, , 0x00x0)

, 	0x0/home/travis/.gimme/versions/go/src/io/io.go)

:	325/home/travis/.gimme/versions/go/src/os/exec.go +:0x58115

 +0x2b

encoding/gob.decodeUintReader(os/exec.(*Cmd).Wait0x894840(, 0xc42021f8c00xc4201ffe00, , 0xc4203ca3c00xc420459b30, , 0xc4200347900x9)

, 	0x9/home/travis/.gimme/versions/go/src/os/exec/exec.go, :0x59cea7434,  +0xc4203c5d280x6d, 

0xc4203c5d30, main.(*builder).runTest.func10x4532e0()

0xc4204574a0, 	0xc42021f8c0/home/travis/.gimme/versions/go/src/encoding/gob/decode.go)

:	119/home/travis/.gimme/versions/go/src/cmd/go/test.go +:0x631145

 +0x2bencoding/gob.(*Decoder).recvMessage

(0xc4204bde80created by , main.(*builder).runTest0xc4203c5d28

)

	/home/travis/.gimme/versions/go/src/encoding/gob/decoder.go:76 +0x57

encoding/gob.(*Decoder).decodeTypeSequence(0xc4204bde80, 0x75c900, 	0xc4204bde80/home/travis/.gimme/versions/go/src/cmd/go/test.go)

:1146 +	0xb13/home/travis/.gimme/versions/go/src/encoding/gob/decoder.go

:

140 +goroutine 0x16f21

 [selectencoding/gob.(*Decoder).DecodeValue, (80xc4204bde80 minutes, ]:

0x719d40, 0xc420409180, 0x16, 0x0, main.(*builder).do.func20x0()

0xc420487650, 	0xc420425480/home/travis/.gimme/versions/go/src/encoding/gob/decoder.go, :0xc4202980c0208)

 +0xd8	

/home/travis/.gimme/versions/go/src/cmd/go/build.go:encoding/gob.(*Decoder).Decode1346( +0xc4204bde800x1bd, 

0x719d40created by , main.(*builder).do0xc420409180

, 0x772b3f, 0x4115af	)

/home/travis/.gimme/versions/go/src/cmd/go/build.go:	1362/home/travis/.gimme/versions/go/src/encoding/gob/decoder.go +:0x4a5185

 +

0x16dgoroutine 

22 [github.com/01org/ciao/ssntp.(*session).Readselect(, 0xc42014c2308 minutes, ]:

0x719d40, 0xc420409180, 0x20, 0x0main.(*builder).runTest)

(	0xc420425480/home/travis/gopath/src/github.com/01org/ciao/ssntp/session.go, :0xc4201f0270194,  +0xc420251e700x5e, 

0x514c23)

github.com/01org/ciao/ssntp.handleSSNTPClient(0xc4203296a0, 0x89aca0, 0xc420343180	)

/home/travis/.gimme/versions/go/src/cmd/go/test.go:	1148/home/travis/gopath/src/github.com/01org/ciao/ssntp/server.go +:0xfc5172

 +0x234

main.(*builder).do.func1(created by 0xc4201f0270github.com/01org/ciao/ssntp.(*Server).Serve)

	/home/travis/.gimme/versions/go/src/cmd/go/build.go:1297 +	0x7d/home/travis/gopath/src/github.com/01org/ciao/ssntp/server.go

:298main.(*builder).do.func2 +(0xb1f0xc420487650

, 

0xc420425480, goroutine 0xc4202980c057)

 [IO wait	, /home/travis/.gimme/versions/go/src/cmd/go/build.go8: minutes1356]:

 +0x145

created by net.runtime_pollWaitmain.(*builder).do(

0x7f2a230db9c0, 0x72	, /home/travis/.gimme/versions/go/src/cmd/go/build.go0xd:)

1362 +	0x4a5/home/travis/.gimme/versions/go/src/runtime/netpoll.go

:

160goroutine  +260x59 [

chan receivenet.(*pollDesc).wait, (80xc42005faa0 minutes, ]:

0x72, 0x8962c0, 0x893448)

	/home/travis/.gimme/versions/go/src/net/fd_poll_runtime.go:75main.processSignals.func1 +(0x380xc420457320

)

net.(*pollDesc).waitRead(	0xc42005faa0/home/travis/.gimme/versions/go/src/cmd/go/signal.go:, 210xc420326400 +, 0x400x400

)

	created by /home/travis/.gimme/versions/go/src/net/fd_poll_runtime.gomain.processSignals:

80 +	0x34/home/travis/.gimme/versions/go/src/cmd/go/signal.go

:23net.(*netFD).Read +(0x930xc42005fa40

, 

0xc420326400goroutine , 250x400 [, select0x400, , 80x0 minutes, , locked to thread0x8962c0]:

, 0x893448)

	/home/travis/.gimme/versions/go/src/net/fd_unix.go:243 +runtime.gopark0x181(

0x862d28net.(*conn).Read, (0x00xc420034878, , 0x83d3f50xc420326400, , 0x60x400, , 0x180x400, , 0x20x0)

, 0x0	, /home/travis/.gimme/versions/go/src/runtime/proc.go0x0:)

259	 +/home/travis/.gimme/versions/go/src/net/net.go0x13a:

173 +runtime.selectgoImpl0x70(

0xc42049f730, crypto/tls.(*block).readFromUntil0x0(, 0xc4203f8f600x18, )

0x7f2a230dc080, 0xc420034878, 0x5, 0xc420034878, 0x0)

	/home/travis/.gimme/versions/go/src/crypto/tls/conn.go:472 +0x91

crypto/tls.(*Conn).readRecord	(/home/travis/.gimme/versions/go/src/runtime/select.go0xc420342e00:, 4230x75c917 +, 0x11d00xc420342f00

, runtime.selectgo0xc420453b28()

0xc42049f730	)

/home/travis/.gimme/versions/go/src/crypto/tls/conn.go	:/home/travis/.gimme/versions/go/src/runtime/select.go574: +2380xc4 +

0x1c

crypto/tls.(*Conn).Readruntime.ensureSigM.func1((0xc420342e00)

, 0xc420370000, 0x1000, 0x1000, 0x0, 0x0, 0x0)

	/home/travis/.gimme/versions/go/src/crypto/tls/conn.go:1109 +0x116

	bufio.(*Reader).fill/home/travis/.gimme/versions/go/src/runtime/signal1_unix.go(:0xc4201ffb00304)

 +0x2f3	

/home/travis/.gimme/versions/go/src/bufio/bufio.goruntime.goexit:()

	/home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:2163 +0x1

rax    0xfffffffffffffffc

rbx    0x0

rcx    0xffffffffffffffff

rdx    0x0

rdi    0xa1d778

rsi    0x0

rbp    0x7f26108d5d98

rsp    0x7f26108d5d50

r8     0x0

r9     0x0

r10    0x7f26108d5d88

r11    0x246

r12    0x097

 +r13    0x00x10b

r14    0x7f26108d69c0bufio.(*Reader).Read

(r15    0xc4201ffb000x7f26108d6700, 

0xc420459720rip    , 0x4cd9530x1

, rflags 0x90x246, 

0x0cs     , 0x330x0

, fs     0x00x0)

gs     0x0	

/home/travis/.gimme/versions/go/src/bufio/bufio.go:209 +0x183

io.ReadAtLeast(0x894840, 0xc4201ffb00, 0xc420459720, 0x1, 0x9, 0x1, 0xc4201ffa01, 0xc42014c1e0, 0x0)

	/home/travis/.gimme/versions/go/src/io/io.go:307 +0xa4

io.ReadFull(0x894840, 0xc4201ffb00, 0xc420459720, 0x1, 0x9, 0xc4201ffb60, 0xc420342e00, 0xc4204bdd80)

	/home/travis/.gimme/versions/go/src/io/io.go:325 +0x58

encoding/gob.decodeUintReader(0x894840, 0xc4201ffb00, 0xc420459720, 0x9, 0x9, 0x59cea7, 0xc420453d58, 0xc420453d60, 0x4532e0)

	/home/travis/.gimme/versions/go/src/encoding/gob/decode.go:119 +0x63

encoding/gob.(*Decoder).recvMessage(0xc4204bdd80, 0xc420453d58)

	/home/travis/.gimme/versions/go/src/encoding/gob/decoder.go:76 +0x57

encoding/gob.(*Decoder).decodeTypeSequence(0xc4204bdd80, 0x75c900, 0xc4204bdd80)

	/home/travis/.gimme/versions/go/src/encoding/gob/decoder.go:140 +0x16f

encoding/gob.(*Decoder).DecodeValue(0xc4204bdd80, 0x719d40, 0xc420409280, 0x16, 0x0, 0x0)

	/home/travis/.gimme/versions/go/src/encoding/gob/decoder.go:208 +0xd8

encoding/gob.(*Decoder).Decode(0xc4204bdd80, 0x719d40, 0xc420409280, 0x772b3f, 0x507ee5)

	/home/travis/.gimme/versions/go/src/encoding/gob/decoder.go:185 +0x16d

github.com/01org/ciao/ssntp.(*session).Read(0xc42014c1e0, 0x719d40, 0xc420409280, 0x0, 0x0)

	/home/travis/gopath/src/github.com/01org/ciao/ssntp/session.go:194 +0x5e

github.com/01org/ciao/ssntp.(*Client).handleSSNTPServer(0xc420089680)

	/home/travis/gopath/src/github.com/01org/ciao/ssntp/client.go:119 +0x120

created by github.com/01org/ciao/ssntp.(*Client).Dial

	/home/travis/gopath/src/github.com/01org/ciao/ssntp/client.go:342 +0x737

rax    0xca

rbx    0x0

rcx    0xffffffffffffffff

rdx    0x0

rdi    0x8b65d0

rsi    0x0

rbp    0x7ffda061a138

rsp    0x7ffda061a0f0

r8     0x0

r9     0x0

r10    0x0

r11    0x286

r12    0x40000

r13    0x1

r14    0x1

r15    0x1

rip    0x45d151

rflags 0x286

cs     0x33

fs     0x0

gs     0x0
```

**Comment by tpepper** [comment]
@markdryan do you have a failed job number in travis?  Github tends to clobber the test-cases output from a readability standpoint.  I'm missing whether the above is a hang, or just the timeout leading to a fail.

The ones I've seen haven't been hangs so much as the test Results channels timing out.  They've got a relatively short timeout, relative to the time it takes a ciao client to reconnect to the server when the server goes offline.  The clients often take 2, sometimes take 3, and rarely take 4 retries to re-connect, with a cumulative elapsed time growing.  The server should be back online very quickly (say 2seconds), but seemingly because of variability in the underlying virtual environment of the Travis test run, sometimes it's taking longer (say 10seconds).  Depending on the randomness added in the client retries, it sometimes happens that the client sleeps between reconnects on the order of 1second, then 1second, then 1second, then 40seconds.  I've tried to describe this in https://github.com/01org/ciao/commit/0e16917936eabe454ada1df8bc0bc601d4a4a954

I can change these timeouts to something longer, like 60s.  The timeout is helpful to diagnose a hang.  But we're tripping the time out today mostly for things that aren't actually hangs.

I could also remove the timeout, since it's proved problematic.  Go test does have it's own hang checking.

**Comment by tpepper** [comment]
Here's an example of one that clearly hit the 25s timeout:
https://travis-ci.org/01org/ciao/jobs/161094052

'''
ciao-scheduler     TestReconnects                           26.03s     FAIL   
ciao-scheduler     TestTenantAdded                          25.00s     FAIL   
ciao-scheduler     TestTenantRemoved                        25.00s     FAIL
'''

**Comment by markdryan** [comment]
@tpepper I'm afraid I don't.  The problem is that when we get these sorts of failures we restart the builds to get Travis's approval for the PR.  When we do this the log of the failed build gets overwritten, which is why I copied the logs here.  Guess I didn't copy enough info.  Sorry.  But what I can say is this was definitely a hang.  test-cases sent an abort signal to the instance of go test running the testutil package, which is why you see most of the tests have a status of not run.  From the logs it looks like TestReconnects was the test that hung.

**Comment by markdryan** [comment]
The other tell-tale sign is the running time of the build.  Of course you can't see this in the issue report but the build took about 15 minutes to run or rather to fail.  This is typical of builds that hang.

**Comment by markdryan** [comment]
@tpepper I also saw one of those 25 second hangs yesterday and I entered a separate bug

https://github.com/01org/ciao/issues/581
