### ISSUE TITLE
launcher sometimes hangs on startup

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#591]
Sometimes, maybe about 1 in 20 times, I can get launcher to hang on startup.  When I quit it it does not quit cleanly.  Here are the stack trace and logs.

```
sudo ./ciao-launcher --logtostderr -cert tests/ciao-launcher-server/cert-client-localhost.pem -cacert tests/ciao-launcher-server/CAcert-server-localhost.pem --with-ui=nc  -v=2 
I0920 04:28:10.437134   23977 main.go:612] Starting Launcher
I0920 04:28:10.437412   23977 main.go:547] Initial nofile limits: cur 1024 max 65536
I0920 04:28:10.437520   23977 main.go:559] Updated nofile limits: cur 65536 max 65536
I0920 04:28:10.437524   23977 main.go:630] Launcher will allow a maximum of 13107 instances
I0920 04:28:10.444279   23977 ssntp.go:889] SSNTP Info: c2c07791-7b45-4c0f-a26f-aa3d232541ef connecting to localhost:8888
I0920 04:28:10.475788   23977 ssntp.go:889] SSNTP Info: Connected
I0920 04:28:10.476455   23977 ssntp.go:889] SSNTP Info: Sending CONNECT
I0920 04:28:10.477653   23977 ssntp.go:889] SSNTP Info: Waiting for CONNECTED
I0920 04:28:10.478964   23977 ssntp.go:889] SSNTP Info: Received CONNECTED frame:
	Major 0
	Minor 1
	Type STATUS
	Op CONNECTED
	Role Scheduler-
	Source 8c949471-8427-4ce4-9c14-f5c0c12451bc
	Destination c2c07791-7b45-4c0f-a26f-aa3d232541ef

I0920 04:28:10.481664   23977 ssntp.go:889] SSNTP Info: Done with connection
I0920 04:28:10.482348   23977 main.go:145] connected
I0920 04:28:10.482366   23977 ssntp.go:889] SSNTP Info: Waiting for next frame
^CI0920 04:28:10.781203   23977 main.go:577] Received terminating signal.  Waiting for server loop to quit
W0920 04:28:11.781862   23977 main.go:587] Server Loop did not exit within 1 second quitting
panic: Server Loop did not exit within 1 second quitting

goroutine 1 [running]:
panic(0x7a8d20, 0xc420100350)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.startLauncher(0x0)
	/home/markus/go/src/github.com/01org/ciao/ciao-launcher/main.go:593 +0x598
main.main()
	/home/markus/go/src/github.com/01org/ciao/ciao-launcher/main.go:636 +0x2c5

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 19 [chan receive]:
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0xc05b20)
	/home/markus/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:882 +0x7a
created by github.com/01org/ciao/vendor/github.com/golang/glog.init.1
	/home/markus/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:410 +0x21d

goroutine 20 [syscall]:
os/signal.signal_recv(0xbf06a0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 21 [select, locked to thread]:
runtime.gopark(0x875e90, 0x0, 0x83b199, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc42001ff30, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc42001ff30)
	/usr/local/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:304 +0x2f3
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [chan send (nil chan)]:
main.processCommand(0xbf3d20, 0xc420126000, 0xc4200ede80, 0x0)
	/home/markus/go/src/github.com/01org/ciao/ciao-launcher/main.go:296 +0xa23
main.connectToServer(0xc420060780, 0xc4200607e0)
	/home/markus/go/src/github.com/01org/ciao/ciao-launcher/main.go:474 +0x903
created by main.startLauncher
	/home/markus/go/src/github.com/01org/ciao/ciao-launcher/main.go:571 +0x234

goroutine 6 [chan send]:
main.connectToServer.func2(0xc4200100e0, 0xc420124000, 0xc420014120)
	/home/markus/go/src/github.com/01org/ciao/ciao-launcher/main.go:414 +0xa4
created by main.connectToServer
	/home/markus/go/src/github.com/01org/ciao/ciao-launcher/main.go:415 +0x2a0

goroutine 8 [IO wait]:
net.runtime_pollWait(0x7f51491d6f78, 0x72, 0x4)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420054370, 0x72, 0xc4200327a0, 0xc420066000)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420054370, 0xbee7e0, 0xc420066000)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc420054310, 0xc420029c00, 0x400, 0x400, 0x0, 0xbee7e0, 0xc420066000)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc420026078, 0xc420029c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
crypto/tls.(*block).readFromUntil(0xc420137260, 0x7f51491d7038, 0xc420026078, 0x5, 0xc420026078, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:472 +0x91
crypto/tls.(*Conn).readRecord(0xc42013b180, 0x875f17, 0xc42013b280, 0x300000002)
	/usr/local/go/src/crypto/tls/conn.go:574 +0xc4
crypto/tls.(*Conn).Read(0xc42013b180, 0xc420224000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1109 +0x116
bufio.(*Reader).fill(0xc420014ae0)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Read(0xc420014ae0, 0xc420168ed0, 0x1, 0x9, 0x0, 0x0, 0x440928)
	/usr/local/go/src/bufio/bufio.go:209 +0x1bc
io.ReadAtLeast(0xbebfa0, 0xc420014ae0, 0xc420168ed0, 0x1, 0x9, 0x1, 0x4ceee0, 0xc05b30, 0x4cf0c9)
	/usr/local/go/src/io/io.go:307 +0xa4
io.ReadFull(0xbebfa0, 0xc420014ae0, 0xc420168ed0, 0x1, 0x9, 0xc400000000, 0x4a32ff, 0xc05b30)
	/usr/local/go/src/io/io.go:325 +0x58
encoding/gob.decodeUintReader(0xbebfa0, 0xc420014ae0, 0xc420168ed0, 0x9, 0x9, 0x5d9ea7, 0xc420032d78, 0xc420032d88, 0x484410)
	/usr/local/go/src/encoding/gob/decode.go:119 +0x63
encoding/gob.(*Decoder).recvMessage(0xc42000ce00, 0xc420032d78)
	/usr/local/go/src/encoding/gob/decoder.go:76 +0x57
encoding/gob.(*Decoder).decodeTypeSequence(0xc42000ce00, 0x875f00, 0xc42000ce00)
	/usr/local/go/src/encoding/gob/decoder.go:140 +0x16f
encoding/gob.(*Decoder).DecodeValue(0xc42000ce00, 0x802680, 0xc4200fa640, 0x16, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:208 +0xd8
encoding/gob.(*Decoder).Decode(0xc42000ce00, 0x802680, 0xc4200fa640, 0xc05b20, 0xc41fff82cd)
	/usr/local/go/src/encoding/gob/decoder.go:185 +0x16d
github.com/01org/ciao/ssntp.(*session).Read(0xc42016d3b0, 0x802680, 0xc4200fa640, 0x0, 0x0)
	/home/markus/go/src/github.com/01org/ciao/ssntp/session.go:194 +0x5e
github.com/01org/ciao/ssntp.(*Client).handleSSNTPServer(0xc420126018)
	/home/markus/go/src/github.com/01org/ciao/ssntp/client.go:119 +0x120
created by github.com/01org/ciao/ssntp.(*Client).Dial
	/home/markus/go/src/github.com/01org/ciao/ssntp/client.go:342 +0x737
```

**Comment by markdryan** [comment]
Okay, it seems to be a race condition in launcher.   The issue is that the ConnectNotify is sending a command before the Dial returns.  The command cannot be processed as the overseer has not started.  The Dial return cannot be processed as the serverloop is blocking on trying to send a command to the overseer.

**Comment by markdryan** [comment]
Note I got the full stack trace above because I added  debug.SetTraceback to main.go before we call the panic.  Could you add this in when fixing the bug?

**Comment by markdryan** [comment]
Look at the code a bit more I think the issue is that the case <-dialCh: statement shouldn't be in the for loop, as it's only going to ever get called once.  So we should have

```
select {
	case err := <-dialCh:
             ...
       	case <-doneCh:
           ...
}

for {
  select {
	       	case <-doneCh:
                    ...
                case cmd := <-client.cmdCh:
                    ...
   }
}
```

This will also allow us to get rid of the dialing boolean.  It won't be needed any more.  The only issue is that this might push us over the gocyclo limit.
