### ISSUE TITLE
ciao-cli: instance show prints golang trace if no -instance match

### ISSUE THREAD

**Issue by tpepper** [01org/ciao#916]
```
$ ciao-cli instance show -instance c8e37390-a838-4438-94ec-148bbb73fc84
F1201 16:48:03.005251   11538 instance.go:826] ciao-cli FATAL: HTTP Error [500] for [GET https://tcpepper-ciaosinglevm:8774/v2.1/f71cbf58a71d454ab932b2db82e88497/servers/c8e37390-a838-4438-94ec-148bbb73fc84]: {"error":{"code":500,"name":"Internal Server Error","message":"Instance not found"}}
null
goroutine 1 [running]:
github.com/01org/ciao/vendor/github.com/golang/glog.stacks(0x94a300, 0xc400000000, 0x12b, 0x2a7)
	/usr/src/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:769 +0xa5
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).output(0x92dfc0, 0xc400000003, 0xc42044c300, 0x908daa, 0xb, 0x33a, 0x0)
	/usr/src/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:720 +0x357
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).printDepth(0x92dfc0, 0xc400000003, 0x1, 0xc42012dd70, 0x1, 0x1)
	/usr/src/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:646 +0x126
github.com/01org/ciao/vendor/github.com/golang/glog.FatalDepth(0x1, 0xc42012dd70, 0x1, 0x1)
	/usr/src/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:1134 +0x5d
main.fatalf(0xc4200d2780, 0xeb, 0x0, 0x0, 0x0)
	/usr/src/go/src/github.com/01org/ciao/ciao-cli/main.go:132 +0x126
main.(*instanceShowCommand).run(0xc420072580, 0xc42000c130, 0x0, 0x0, 0xc42000c130, 0x0)
	/usr/src/go/src/github.com/01org/ciao/ciao-cli/instance.go:826 +0x33b
main.(*command).run(0x92c4b0, 0xc42000c130, 0x0, 0x0, 0xc42009cbc8, 0x0)
	/usr/src/go/src/github.com/01org/ciao/ciao-cli/main.go:58 +0x15b
main.main()
	/usr/src/go/src/github.com/01org/ciao/ciao-cli/main.go:466 +0xf7
```

It would be a lot nicer if this printed a clean message stating "Instance not found" and no more.

**Comment by markdryan** [comment]
Agreed.  This applies to all error conditions encountered by ciao-cli not just instance  show.  The stack trace is fairly useless and it obscures the main error.
